### PR TITLE
created skeleton UI for user signup and added create function in the …

### PR DESCRIPTION
**Pull request by liumiche**
…backend for user and shelter

### CODE REVIEW

**Comment by chris-befoul** [comment]
Your code looks good Michelle, I had never heard of bcrypt before and had to look into it to what it does and really cool stuff. I may have overlooked it but how did you get your form to submit to your backend server to send data to datastore? For mine I had utilized the fetch approach to connect and send data via post method and wanted to make sure I wasn't taking the long road if there is an easier way.

**Comment by liumiche** [comment]
I haven't connected react frontend to the backend but I plan on using fetch too. That's on my next week's agenda. I just want to get the server code merged first so Vincent can build the sign-in system on top of what I have for signup.

**Comment by chris-befoul** [comment]
No worries, I just wanted to make sure I wasn't overcomplicating things on my end! I will go ahead and approve.

**Review by chris-befoul — APPROVED** [review]
Great work Michelle!

**Review by vincentchen137 — APPROVED** [review]
Looks good to me! Thanks Michelle!

**Pull request merged**
